CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  store_id BIGINT,
  customer_id BIGINT,
  delivery_partner_id BIGINT,
  cart_id BIGINT,
  payment_mode VARCHAR,
  delivery_status VARCHAR,
  total_amount MONEY,
  FOREIGN KEY (store_id) REFERENCES store(id),
  FOREIGN KEY (customer_id) REFERENCES customer(id),
  FOREIGN KEY (delivery_partner_id) REFERENCES delivery_partner(id),
  FOREIGN KEY (cart_id) REFERENCES cart(id),
  PRIMARY KEY(id)
);
